<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Tempering" Id="{c38b8cdc-1856-4303-be47-22d52c579c56}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Tempering
VAR_INPUT
	bExecute		: BOOL;
END_VAR
VAR_OUTPUT
	bDone			: BOOL;
	bError			: BOOL;
	wErrorID		: BOOL;
END_VAR
VAR
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Tempering">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>